source_id: tommy_us
name: Tommy Hilfiger US
country: US
currency: USD
base_url: https://usa.tommy.com
crawl_type: http_with_playwright_fallback
crawl_interval_minutes: 60
enabled: true

entrypoints:
  coupons:
    url: https://usa.tommy.com/en/tommy-hilfiger-coupons
    parser: tommy_coupon_page_parser

  sale:
    url: https://usa.tommy.com/en/sale
    parser: tommy_sale_listing_parser
